# Generated by Django 4.1.5 on 2023-01-17 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogDetails',
            fields=[
                ('log_code', models.CharField(default=main.models.random_code_generator, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20, null=True)),
                ('address', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tourists', to='main.logdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_classification', models.CharField(choices=[('private', 'private'), ('public', 'public')], max_length=20, null=True)),
                ('vehicle_type', models.CharField(choices=[('van', 'van'), ('bus', 'bus'), ('motorcycle', 'motorcycle'), ('pick-up', 'pick-up'), ('suv', 'suv'), ('car', 'car'), ('others', 'others')], max_length=20, null=True)),
                ('description', models.TextField()),
                ('drivers', models.ManyToManyField(related_name='vehicle_used', to='main.tourist')),
                ('log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='main.logdetails')),
                ('passengers', models.ManyToManyField(to='main.tourist')),
            ],
        ),
    ]
