# Generated by Django 4.1.5 on 2023-01-20 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='passengers',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='passengers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tourist'),
        ),
    ]
