# Generated by Django 4.1.5 on 2023-01-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_tourist_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='log',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='log',
            field=models.ManyToManyField(to='main.logdetails'),
        ),
    ]
