# Generated by Django 4.1.5 on 2023-01-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_vehicle_passengers_vehicle_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='contact_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
