# Generated by Django 4.1.5 on 2023-01-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('office_admin', 'office_admin'), ('staff_only', 'staff_only')], default='staff_only', max_length=20, null=True),
        ),
    ]
