# Generated by Django 4.1.5 on 2023-01-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('staff_only', 'staff_only'), ('office_admin', 'office_admin')], default='staff_only', max_length=20),
        ),
    ]
